In [3]:
import torch

In [5]:
x = torch.empty(1)
print(x)

tensor([0.])


In [6]:
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [8]:
# 4D
x = torch.empty(2, 2, 2, 3)
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [9]:
x = torch.rand(2, 2)
print(x)

tensor([[0.8026, 0.6605],
        [0.7240, 0.1220]])


In [11]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [12]:
x = torch.ones(2, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [14]:
print(x.dtype)

torch.float32


In [17]:
# dtype parameter (int, float16, float64, double)
x = torch.ones(2, 4, dtype=torch.float64)
print(x)
print(x.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
torch.float64


In [18]:
# Print size of the tensor
print(x.size())

torch.Size([2, 4])


In [20]:
# Tensor from a list
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [21]:
#Basic Operations

x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.1661, 0.4089],
        [0.5050, 0.5727]])
tensor([[0.3156, 0.0288],
        [0.0089, 0.4086]])


In [22]:
z = x + y # Elementwise addition (torch.add(x, y))
print(z)

tensor([[0.4817, 0.4377],
        [0.5139, 0.9813]])


In [24]:
# Every function that has a trailing underscore performs an inplace operation
y.add_(x) # inplace addition (modifies y by adding elements of x to y)
print(y)

tensor([[0.6478, 0.8466],
        [1.0189, 1.5541]])


In [25]:
z = x - y
z = torch.sub(x, y)
print(z)

tensor([[-0.4817, -0.4377],
        [-0.5139, -0.9813]])


In [26]:
z = x - y
z = torch.mul(x, y)
print(z)

tensor([[0.1076, 0.3462],
        [0.5146, 0.8901]])


In [27]:
torch.div(x, y)

tensor([[0.2564, 0.4830],
        [0.4957, 0.3685]])

In [28]:
# Slicing operations
x = torch.rand(5, 3)
print(x)

tensor([[0.4979, 0.9542, 0.7921],
        [0.4384, 0.6363, 0.3968],
        [0.5920, 0.5664, 0.0193],
        [0.3448, 0.3354, 0.7783],
        [0.3631, 0.0016, 0.0494]])


In [29]:
# all values in the first column of every row [row: col]
print([x[:, 0]]) 

[tensor([0.4979, 0.4384, 0.5920, 0.3448, 0.3631])]


In [30]:
# Second row of all the columns
print(x[1, :])

tensor([0.4384, 0.6363, 0.3968])


In [33]:
# element in row 2 and position at position 1
print(x[1, 1].item()) # .item gets the actual value in a tesnsor with one value

0.6363447308540344


In [39]:
# Reshaping
x = torch.rand(4, 4)
print(x)
print(x.shape)

tensor([[0.5373, 0.4824, 0.0804, 0.8016],
        [0.6486, 0.1017, 0.9076, 0.2415],
        [0.3664, 0.4018, 0.0595, 0.9502],
        [0.9184, 0.9563, 0.5973, 0.3285]])
torch.Size([4, 4])


In [36]:
y = x.view(16)

In [37]:
print(y)

tensor([0.5221, 0.1176, 0.1878, 0.1777, 0.5023, 0.1017, 0.9285, 0.8197, 0.4984,
        0.7506, 0.7531, 0.6120, 0.7416, 0.1445, 0.6525, 0.8035])


In [38]:
print(y.shape)

torch.Size([16])


In [40]:
y = x.view(-1, 8)

In [42]:
y.shape

torch.Size([2, 8])

In [43]:
# Numpy to torch tensor
import numpy as np

In [45]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [47]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [48]:
print(type(b))

<class 'numpy.ndarray'>


In [50]:
a.add_(1) # They both point to the same memory location
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [51]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [52]:
torch.tensor(a)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [53]:
# They both point to the same memory
a += 85 
print(a)
print(b)

[86. 86. 86. 86. 86.]
tensor([86., 86., 86., 86., 86.], dtype=torch.float64)


In [54]:
# cuda
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    # or
    y = torch.ones(5)
    y = y.to(device)
    
    z = x + y
    z.numpy() # generates an error: numpy can only work on cpu tensorfs
    
    z = z.to("cpu")
else:
    device = torch.device('cpu')

In [56]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
