In [1]:
import torch

In [2]:
# Calculating Gradients : Important for model optimizations
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.4242, -0.3894,  1.0771], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([1.5758, 1.6106, 3.0771], grad_fn=<AddBackward0>)


In [4]:
# multiplication
z = y * y * 2
print(z)

tensor([ 4.9661,  5.1879, 18.9367], grad_fn=<MulBackward0>)


In [5]:
# Mean
# z = z.mean()
# print(z)

In [6]:
z.backward() # dz/dx : z has to be a scalar value if not backward() requires a vector
# v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32) usually the scalar opeara
print(x.grad)

RuntimeError: grad can be implicitly created only for scalar outputs